### PR TITLE
ansible additions

### PR DESCRIPTION
**Pull request by hvisage**

### CODE REVIEW

**Comment by timlinux** [comment]
Just please note that this is a public repo - I don't know if it is good to just directly merge t4a stuff in here - better to sanitise the PR first and then merge it. @gubuntu can comment on if they will be ok with having their config stuff in our history.

**Comment by gubuntu** [comment]
I agree with @timlinux. @hvisage, it's fine to use patterns from the T4A ansible code base but please refrain from copying wholesale and definitely sanitise. Also, Kartoza default practice is to merge your own PRs into origin.

**Comment by hvisage** [comment]
PRs??

---
replied from my small phone :)
--
Hendrik Visage

**Comment by hvisage** [comment]
The sanitization of some parts Ive missed, ir was part if what I wanted to
do as we progress, wasnt appear of the publicness vs private.

---
replied from my small phone :)
--
Hendrik Visage

**Pull request closed without merging**
